# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='应用编号')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='说明')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='周期名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='周期代码')),
                ('minutes', models.IntegerField(blank=True, null=True, verbose_name='分钟')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Dictindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='说明')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Dictlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='条目名称')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='说明')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='状态')),
                ('dictindex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Dictindex')),
            ],
        ),
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='功能名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('funtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('app', models.ManyToManyField(to='datacenter.App')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='datacenter.Fun', verbose_name='父节点')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='组名')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='说明')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('fun', models.ManyToManyField(to='datacenter.Fun')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='数据源代码')),
                ('sourcetype', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('connection', models.CharField(blank=True, max_length=500, null=True, verbose_name='连接串')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='datacenter.Source', verbose_name='父节点')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='存储名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='存储代码')),
                ('tablename', models.CharField(blank=True, max_length=200, verbose_name='表名')),
                ('storagetype', models.CharField(blank=True, max_length=20, null=True, verbose_name='存储类型')),
                ('validtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='数据有效时间')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='指标代码')),
                ('operationtype', models.CharField(blank=True, max_length=20, verbose_name='操作类型')),
                ('cycletype', models.CharField(blank=True, max_length=20, verbose_name='周期类型')),
                ('businesstype', models.CharField(blank=True, max_length=20, verbose_name='业务类型')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='机组')),
                ('magnification', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='倍率')),
                ('digit', models.IntegerField(blank=True, null=True, verbose_name='保留位数')),
                ('cumulative', models.CharField(max_length=20, verbose_name='是否累计')),
                ('upperlimit', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='上限')),
                ('lowerlimit', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='下限')),
                ('formula', models.CharField(max_length=2000, verbose_name='公式')),
                ('sourcetable', models.CharField(max_length=2000, verbose_name='数据源表')),
                ('sourcefields', models.CharField(max_length=2000, verbose_name='数据源字段')),
                ('sourceconditions', models.CharField(max_length=2000, verbose_name='数据源条件')),
                ('sourcesis', models.CharField(max_length=2000, verbose_name='数据源sis点')),
                ('storagefields', models.CharField(max_length=2000, verbose_name='存储字段')),
                ('storagetag', models.CharField(max_length=200, verbose_name='存储标识')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='说明')),
                ('adminapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_adminapp_set', to='datacenter.App')),
                ('app', models.ManyToManyField(related_name='target_app_set', to='datacenter.App')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cycle')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Source')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGUID', models.CharField(max_length=50, null=True, verbose_name='GUID')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('usertype', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='说明')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司')),
                ('tell', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('forgetpassword', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改密码地址')),
                ('group', models.ManyToManyField(to='datacenter.Group')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='datacenter.UserInfo', verbose_name='父节点')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
