# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-29 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_auto_20190325_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='信息名称')),
                ('default_value', models.CharField(max_length=100, verbose_name='默认值')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='报表名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='报表编码')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名称')),
                ('report_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='报表类型')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.App')),
            ],
        ),
        migrations.AlterField(
            model_name='dictlist',
            name='dictindex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.DictIndex'),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='report_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.ReportModel'),
        ),
    ]
