# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_auto_20190331_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Storage'),
        ),
    ]
