# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-01 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_auto_20190331_1156'),
        ('datacenter', '0003_auto_20190329_1137'),
    ]

    operations = [
    ]
