# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_auto_20190409_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamain',
            name='app',
        ),
        migrations.RemoveField(
            model_name='calculatedata',
            name='datamain',
        ),
        migrations.RemoveField(
            model_name='entrydata',
            name='datamain',
        ),
        migrations.RemoveField(
            model_name='extractdata',
            name='datamain',
        ),
        migrations.AddField(
            model_name='calculatedata',
            name='datadate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='entrydata',
            name='datadate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='extractdata',
            name='datadate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.DeleteModel(
            name='Datamain',
        ),
    ]
