# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0009_auto_20190411_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_info', models.CharField(blank=True, max_length=2000, null=True, verbose_name='报表信息XML')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('person', models.CharField(blank=True, max_length=100, null=True, verbose_name='填报人')),
                ('write_time', models.DateTimeField(blank=True, null=True, verbose_name='填报日期')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.App')),
                ('report_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.ReportModel')),
            ],
        ),
    ]
