# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_reportsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='信息名称')),
                ('value', models.CharField(max_length=100, verbose_name='默认值')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportsubmit',
            name='report_info',
        ),
        migrations.AddField(
            model_name='reportsubmitinfo',
            name='report_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.ReportSubmit'),
        ),
    ]
