# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-11 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0011_auto_20190411_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsubmitinfo',
            old_name='report_model',
            new_name='report_submit',
        ),
    ]
