# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0012_auto_20190411_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmit',
            name='report_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报表时间'),
        ),
        migrations.AlterField(
            model_name='reportsubmit',
            name='write_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日期'),
        ),
    ]
