# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-15 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0013_auto_20190412_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启动时间'),
        ),
        migrations.AddField(
            model_name='source',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近取数时间'),
        ),
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='source',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='状态'),
        ),
    ]
