# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0014_auto_20190415_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='状态'),
        ),
    ]
