# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0015_auto_20190415_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='p_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='进程ID'),
        ),
    ]
