# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0016_source_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='datatype',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='数据类型'),
        ),
    ]
