# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0017_target_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmonitor',
            name='app_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.App', verbose_name='管理应用'),
        ),
        migrations.AddField(
            model_name='processmonitor',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cycle', verbose_name='周期'),
        ),
        migrations.AddField(
            model_name='processmonitor',
            name='p_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='进程ID'),
        ),
        migrations.AddField(
            model_name='processmonitor',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Source', verbose_name='数据源'),
        ),
    ]
