# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0017_target_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedata',
            name='curvaluedate',
            field=models.DateTimeField(null=True, verbose_name='当前值'),
        ),
        migrations.AddField(
            model_name='calculatedata',
            name='curvaluetext',
            field=models.CharField(max_length=20, null=True, verbose_name='当前值'),
        ),
        migrations.AddField(
            model_name='entrydata',
            name='curvaluedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='当前值'),
        ),
        migrations.AddField(
            model_name='entrydata',
            name='curvaluetext',
            field=models.CharField(blank=True, max_length=20, verbose_name='当前值'),
        ),
    ]
