# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0020_processmonitor_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydata',
            name='curvaluedate',
            field=models.DateTimeField(null=True, verbose_name='当前值'),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='curvaluetext',
            field=models.CharField(max_length=20, null=True, verbose_name='当前值'),
        ),
    ]
