# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0021_auto_20200113_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractdata',
            name='curvaluedate',
            field=models.DateTimeField(null=True, verbose_name='当前值'),
        ),
        migrations.AddField(
            model_name='extractdata',
            name='curvaluetext',
            field=models.CharField(max_length=20, null=True, verbose_name='当前值'),
        ),
    ]
