# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-02-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0025_remove_cycle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='schedule_type',
            field=models.IntegerField(choices=[(1, '每日'), (2, '每周'), (3, '每月')], default=1, null=True),
        ),
    ]
