# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-02-10 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0026_cycle_schedule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='code',
        ),
    ]
