# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-02-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0028_remove_storage_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='sourceconditions',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sourcefields',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sourcesis',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sourcetable',
        ),
        migrations.AddField(
            model_name='target',
            name='source_content',
            field=models.TextField(blank=True, null=True, verbose_name='数据源内容'),
        ),
        migrations.AlterField(
            model_name='app',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='calculatedata',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='公式'),
        ),
        migrations.AlterField(
            model_name='dictindex',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='dictlist',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='fun',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='group',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='source',
            name='connection',
            field=models.TextField(blank=True, null=True, verbose_name='连接串'),
        ),
        migrations.AlterField(
            model_name='target',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='公式'),
        ),
        migrations.AlterField(
            model_name='target',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='target',
            name='storagefields',
            field=models.TextField(blank=True, null=True, verbose_name='存储字段'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
    ]
