# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-02-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0030_auto_20200211_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract_error_time', models.DateTimeField(blank=True, null=True, verbose_name='取数失败时间')),
                ('supplement_times', models.IntegerField(blank=True, null=True, verbose_name='补取次数')),
                ('last_supplement_time', models.DateTimeField(blank=True, null=True, verbose_name='最新补取时间')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.App', verbose_name='应用')),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cycle', verbose_name='周期')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Source', verbose_name='数据源')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Target', verbose_name='指标')),
            ],
        ),
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='日志内容')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.App', verbose_name='应用')),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cycle', verbose_name='周期')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Source', verbose_name='数据源')),
            ],
        ),
    ]
