# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-02-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0031_exceptiondata_loginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, default='1', max_length=20, verbose_name='类型：区分固定0/动态1'),
        ),
    ]
