# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-02-17 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0032_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedata',
            name='target',
        ),
        migrations.RemoveField(
            model_name='entrydata',
            name='target',
        ),
        migrations.RemoveField(
            model_name='extractdata',
            name='target',
        ),
        migrations.RemoveField(
            model_name='meterdata',
            name='target',
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='meterdata',
            field=models.IntegerField(blank=True, null=True, verbose_name='电表数据id'),
        ),
        migrations.DeleteModel(
            name='calculatedata',
        ),
        migrations.DeleteModel(
            name='entrydata',
        ),
        migrations.DeleteModel(
            name='extractdata',
        ),
        migrations.DeleteModel(
            name='Meterdata',
        ),
    ]
