# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-03-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0034_auto_20200218_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptiondata',
            name='supplement_times',
            field=models.IntegerField(default=0, null=True, verbose_name='补取次数'),
        ),
    ]
