# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-03-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0035_auto_20200303_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='业务名称')),
                ('code', models.CharField(blank=True, default='', max_length=128, verbose_name='业务编号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='说明')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('core', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否核心业务')),
                ('state', models.CharField(blank=True, default='', max_length=20, verbose_name='状态')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.App', verbose_name='应用')),
            ],
        ),
    ]
