# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-03-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0037_auto_20200312_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Work', verbose_name='业务'),
        ),
    ]
