# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-03-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0038_target_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='fun',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Work', verbose_name='业务'),
        ),
    ]
