# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0040_target_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_repeat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='数据重复时'),
        ),
    ]
