# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0041_target_is_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='常数名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='常数代码')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('unity', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('adminapp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_adminapp_set', to='datacenter.App')),
            ],
        ),
    ]
