# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0042_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True, verbose_name='常数值'),
        ),
    ]
