# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-03-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0043_constant_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_script_path', models.CharField(blank=True, default='', max_length=256, verbose_name='POWERSHELL脚本存放位置')),
                ('report_file_path', models.CharField(blank=True, default='', max_length=256, verbose_name='报表服务器存放文件路径')),
                ('web_server', models.CharField(blank=True, default='', max_length=256, verbose_name='Web服务器地址:127.0.0.1:8000')),
                ('report_server', models.CharField(blank=True, default='', max_length=256, verbose_name='报表服务器地址')),
                ('username', models.CharField(blank=True, default='', max_length=256, verbose_name='报表服务器用户名')),
                ('password', models.CharField(blank=True, default='', max_length=256, verbose_name='报表服务器密码')),
            ],
        ),
    ]
