# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-04-08 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacenter', '0044_reportserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datadate', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('adminapp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportlog_adminapp_set', to='datacenter.App')),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cycle', verbose_name='周期')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Work', verbose_name='业务')),
            ],
        ),
    ]
