# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-04-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0045_reportinglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinglog',
            name='cycle',
        ),
        migrations.AddField(
            model_name='reportinglog',
            name='cycletype',
            field=models.CharField(blank=True, max_length=20, verbose_name='周期类型'),
        ),
    ]
