# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-04-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0046_auto_20200408_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_time', models.DateTimeField(null=True, verbose_name='启动时间：点击补取的当前时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间：一分钟写一次，系统时间')),
                ('p_state', models.CharField(blank=True, max_length=10, null=True, verbose_name='进程状态：1/0')),
                ('start_time', models.DateTimeField(null=True, verbose_name='补取开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='补取结束时间')),
                ('progress_time', models.DateTimeField(null=True, verbose_name='补取进度时间：一分钟写一次，取数时间')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='状态')),
                ('primary_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.ProcessMonitor', verbose_name='主进程表')),
            ],
        ),
    ]
