# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-04-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0048_supplementprocess_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='data_from',
            field=models.CharField(choices=[('lc', '本地系统'), ('et', '外部系统')], default='lc', max_length=20, null=True, verbose_name='数据来源'),
        ),
    ]
