# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-04-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0049_target_data_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='value',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='常数值'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='finalvalue',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='最终计算值'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='newtable_finalvalue',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='新表最终值'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='newtable_twentyfourdata',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='新表最终走字'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='newtable_value',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='新表差值'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='newtable_zerodata',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='新表起始走字'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='oldtable_finalvalue',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='旧表最终值'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='oldtable_twentyfourdata',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='旧表最终走字'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='oldtable_value',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='旧表差值'),
        ),
        migrations.AlterField(
            model_name='meterchangedata',
            name='oldtable_zerodata',
            field=models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='旧表起始走字'),
        ),
    ]
