# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-04-24 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0051_auto_20200415_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='if_push',
            field=models.CharField(default='0', max_length=20, null=True, verbose_name='是否推送'),
        ),
        migrations.AddField(
            model_name='target',
            name='push_config',
            field=models.TextField(null=True, verbose_name="推送配置:{'dest_fields': ['', ''], 'origin_source': '', 'constraint_fields': [''], 'dest_table': '', 'origin_fields': ['', '']}"),
        ),
    ]
