# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-05-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0052_auto_20200424_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='cumulate_type',
            field=models.CharField(choices=[('qh', '求和'), ('jqpj', '加权平均'), ('sspj', '算术平均')], default='qh', max_length=20, null=True, verbose_name='累计类型'),
        ),
    ]
