# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0054_auto_20200512_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='cumulative',
            field=models.CharField(choices=[('0', '不累计'), ('1', '求和'), ('2', '算术平均'), ('3', '加权平均'), ('4', '非零算术平均')], max_length=20, null=True, verbose_name='累计类型'),
        ),
    ]
