# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0055_auto_20200611_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinglog',
            name='write_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='制表时间'),
        ),
        migrations.AlterField(
            model_name='reportinglog',
            name='datadate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报表时间'),
        ),
    ]
