# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0056_auto_20200722_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, null=True, verbose_name='查询名')),
                ('type', models.CharField(default='', max_length=20, null=True, verbose_name='查询周期类型')),
                ('remark', models.TextField(default='', null=True, verbose_name='查询说明')),
                ('col_data', models.TextField(default='', null=True, verbose_name='指标列JSON信息')),
            ],
        ),
    ]
