# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0057_targetstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetstatistic',
            name='state',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='状态'),
        ),
    ]
