# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0058_targetstatistic_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(blank=True, default='', max_length=64, verbose_name='分钟')),
                ('hour', models.CharField(blank=True, default='', max_length=64, verbose_name='小时')),
                ('day_of_week', models.CharField(blank=True, default='', max_length=64, verbose_name='周中日')),
                ('day_of_month', models.CharField(blank=True, default='', max_length=64, verbose_name='月中日')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='minute',
        ),
        migrations.AddField(
            model_name='subcycle',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cycle', verbose_name='周期'),
        ),
    ]
