# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-07 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0060_auto_20200901_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ad_user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='if_ad_login',
        ),
    ]
