# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0061_auto_20200907_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='if_template',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, null=True, verbose_name='是否公共报表模板'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.App'),
        ),
    ]
