# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0062_auto_20200914_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='指标代码'),
        ),
    ]
