# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0063_auto_20201014_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_electric_energy', models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='#1上网电量')),
                ('s_electric_energy', models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='#2上网电量')),
                ('a_electric_energy', models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='总上网电量')),
                ('extract_time', models.DateTimeField(null=True, verbose_name='取数时间')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='状态')),
            ],
        ),
    ]
