# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0065_target_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='group',
        ),
        migrations.AddField(
            model_name='targetstatistic',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Group', verbose_name='权限组'),
        ),
    ]
