# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-29 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0067_remove_targetstatistic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetstatistic',
            name='group',
            field=models.ManyToManyField(to='datacenter.Group'),
        ),
    ]
