# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-29 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0068_targetstatistic_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetstatistic',
            name='group',
        ),
    ]
