# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0069_remove_targetstatistic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetstatistic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.UserInfo', verbose_name='权限用户'),
        ),
    ]
