# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-11-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0070_targetstatistic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinglog',
            name='operationtype',
            field=models.CharField(blank=True, max_length=20, verbose_name='操作类型'),
        ),
    ]
