# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-11-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0072_fun_if_new_wd'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_select',
            field=models.CharField(max_length=20, null=True, verbose_name='是否查询'),
        ),
    ]
