# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0073_target_is_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubmitinfo',
            name='value',
            field=models.CharField(max_length=2000, verbose_name='默认值'),
        ),
    ]
