# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0074_auto_20201207_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcycle',
            name='min_of_hour',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='时中分'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='schedule_type',
            field=models.IntegerField(choices=[(1, '每日'), (2, '每周'), (3, '每月'), (4, '每小时')], default=1, null=True),
        ),
    ]
