# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0075_auto_20201209_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='登录次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='retry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='重试时间'),
        ),
    ]
