# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0076_auto_20201211_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='登录次数'),
        ),
    ]
