# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-16 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0077_auto_20201211_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='warn_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='报警范围'),
        ),
    ]
