# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2021-03-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0078_target_warn_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetstatistic',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
