# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-06-18 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacenter', '0080_auto_20210401_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycletype', models.CharField(blank=True, max_length=20, verbose_name='周期类型')),
                ('operationtype', models.CharField(blank=True, max_length=20, verbose_name='操作类型')),
                ('datadate', models.DateTimeField(blank=True, null=True, verbose_name='数据时间')),
                ('write_time', models.DateTimeField(blank=True, null=True, verbose_name='变更时间时间')),
                ('before_curvalue', models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='变更前数据')),
                ('after_curvalue', models.DecimalField(decimal_places=7, max_digits=22, null=True, verbose_name='变更后数据')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('adminapp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedatalog_adminapp_set', to='datacenter.App')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Target')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.Work', verbose_name='业务')),
            ],
        ),
    ]
